baseURL = "https://curatedml.netlify.com"
disqusShortname = ""
googleAnalytics = ""
paginate = "10"
summaryLength = "15"
theme = "bigspring"
title = "Curated ML"
[markup.goldmark.renderer]
unsafe = true
